### Basic Appearance

# The field dimensions
# Too small field results in poor evolution
# Too large field is harmful for the performance
fieldWidth = 400
fieldHeight = 250

# One cell will have this many pixels for width and height
pixelScale = 4

# This shapes the existence, location and appearance of the control panel
language = en
legendIsOnRight = true
enableLegend = true
textWidth = 310
fontSize = 16

# The buttons that add food or nuke the life have the configurable radius in cells
smallRadius = 10
largeRadius = 50

# If this is true, a button is added which enables to dump the genome
# of the closest bacteria by the mouse click
enableGenomeDumping = true

# Enables and configures the sound
sound = false
soundFrequency = 48000
soundBufferSize = 128

# Auto-pauses every X epochs, a non-positive value disables the feature
autoPause = 0

# Persistence mechanism that allows caching of expensive computations. Variants are:
# - None: no persistence. This allows interactive actions such as placing monsters, adding food or erasing parts of field.
# - SingleRun("filename", mode): a single-file database for a single simulation run.
#   If the file exists, its stored configuration should match the one currently running.
#   The filename must be in quotation marks.
#   The "mode" should be one of: "read", "append", "validate", where:
#   - "read": the actions are read until there are none, then simulation stops
#   - "append": the actions are read while there are some, then subsequently new actions are computed and written
#   - "validate": behaves like "read" but pretends there are no actions, forces them to be computed,
#                 and then fails if they do not match the record. Useful for testing.
# - ChecksumDir("directory-name", mode): a hierarchical storage with lookups based on config checksums.
#   The directory name must be in quotation marks. If it does not exist, it will be created.
#   The "mode" is as above.
persistence = ChecksumDir("cache", append)

### Life Parameters

# The version of the configuration encoding. This is to support some kind of backward compatibility.
lifeConfigVersion = 1

# The sequence of actions enabled for this run, in this order.
#   The first one corresponds to the last element of the program, the second to the next-to-last, so on.
#   Fork(...) has an argument, which is the mutation operator, the choices are one of: Primitive, Smooth, NoChange.
#   Primitive and Smooth take an argument, the probability to actually try applying changes, should be in (0;1].
# This is the original sequence.
actionSequence = Fork(Smooth(1.0)), RotateMinus, RotatePlus, Move, Eat
# This is "Arina's default" aka in the order of importance.
#    actionSequence = Eat, Move, Fork(Smooth(1.0)), RotatePlus, RotateMinus
# This is "reverted Arina's default" that puts important actions to less mutation-fragile positions.
#    actionSequence = RotateMinus, RotatePlus, Fork(Smooth(1.0)), Move, Eat
# This is the original sequence plus the no-change mutation
#    actionSequence = Fork(Smooth(1.0)), Fork(NoChange), RotateMinus, RotatePlus, Move, Eat
# or the "Carola Doerr"-like exponentially decaying choice of mutations:
#    actionSequence = Fork(Smooth(1.0)), Fork(Smooth(0.1)), Fork(Smooth(0.01)), RotateMinus, RotatePlus, Move, Eat

# The enabled instructions with probabilities of being selected when generating randomly.
# First, the sequence is given.
instructions = Const, MyWeight, MyHealth, FoodAt, DebrisAt, HealthAt, Sin, \
               Cos, Exp, Log, Plus, Minus, Times, Divide, Sigmoid
#   the social intelligence config:
#   instructions = Const, HealthAt, Sin, Cos, Exp, Log, Plus, Minus, Times, Divide, Sigmoid
# Second, their probability weights are given. These are renormalized when parsing.
# If you want to specify probabilities that will not be renormalized, use instructionProbability.XXX instead.
# This is that persisted configurations use.
instructionWeight.Const = 1
instructionWeight.MyWeight = 1
instructionWeight.MyHealth = 1
instructionWeight.FoodAt = 1
instructionWeight.DebrisAt = 1
instructionWeight.HealthAt = 1
instructionWeight.Sin = 1
instructionWeight.Cos = 1
instructionWeight.Exp = 1
instructionWeight.Log = 1
instructionWeight.Plus = 1
instructionWeight.Minus = 1
instructionWeight.Times = 1
instructionWeight.Divide = 1
instructionWeight.Sigmoid = 1

# the initial health of the bacteria
initialHealth = 10

# the initial genome length of the bacteria
initialGenomeLength = 50

# the probability that a cell contains a bacteria initially
initialBacteriaProbability = 0.2

# Random number generator parameters.
# Unset randomSeed to use System.nanoTime().
randomFactory = Xoshiro256PlusPlus
# randomSeed = 249806238651465

# what portion of current effective weight is spent on rotation
rotationCost = 0.01

# what portion of current effective weight is spent on move
moveCost = 0.02

# what part of food is not actually eaten
eatCost = 0.05

# what part of chromosome weight, as energy, is spent on forking
forkCost = 0.1

# what part of spent energy reappears as debris
debrisFromActions = 0.5

# what part of debris disappear
debrisDegradation = 0.02

# what part of debris becomes accessible as energy again
debrisToFood = 0.0

# the expected amount of new food to be generated on first generations
synthesisInit = 0.1

# the expected amount of new food to be generated on infinitely remote generations
synthesisFinal = 0.001

# how fast the amount of new food moves from first to infinitely remote generations
synthesisDecay = 0.001

# how randomly the food is deposited
# this value should be in [0;1] and controls randomness in a linear way:
# - for 0, for the expected food per current cell Q, exactly Q food is deposited
# - for 1, the deposited value is sampled uniformly from [0; 2Q]
synthesisRandomness = 1.0

# the amount of energy to spend on just being alive
idleCost = 0.1

# how much energy can a bacteria keep, relative to genome size
healthMultiple = 10

# how much energy can a bacteria consume in a single Eat action, relative to genome size
healthIncrementMultiple = 1

# how many hot spots (in terms of food) in a row will eventually appear
spotPeriodX = 2

# how many hot spots in a column will eventually appear
spotPeriodY = 1

# how many horizontal space per generation every hot spot will move
spotSpeedX = 0.000094

# how many vertical space per generation every hot spot will move
spotSpeedY = 0.0002

# spots get close to sine distribution with time, this parameter describes by how much
spotDecay = 0.01
